source 'https://rubygems.org'
ruby '2.1.0'
gem 'sinatra'
gem 'mongoid', '~>3.1.6'
gem 'bson_ext'
#gem 'aws-s3'
gem 'rake'
gem 'bcrypt-ruby', '~> 3.0.0', :require => 'bcrypt'
gem 'mini_magick', '~> 3.5.0'
gem 'koala'
gem 'yard-sinatra'
gem 'rack-test'